[package]
name = "yausg"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.9.0"
bevy_rapier3d = { version = "0.19.0", features = ["simd-stable", "debug-render" ] }
