name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup
      run: |
        rustup install 1.65.0
        rustup target add wasm32-unknown-unknown
        cargo build --release --target wasm32-unknown-unknown
        cargo install -f wasm-bindgen-cli
        wasm-bindgen --out-dir ./out/ --target web ./target/wasm32-unknown-unknown/release/yausg.wasm
        
        for f in $(chmod -c -R +r . | awk '{print substr($3, 2, length($3)-2)}')
        do
          echo "::warning::Added read permission to $f"
        done
        tar \
          --dereference --hard-dereference \
          --directory "./out/" \
          -cvf "$RUNNER_TEMP/artifact.tar" \
          --exclude=.git \
          --exclude=.github \
          .
    - name: Upload artifact
      uses: actions/upload-artifact@main
      with:
        name: github-pages
        path: ${{ runner.temp }}/artifact.tar
        retention-days: ${{ 1 }}
