name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: jetli/wasm-bindgen-action@v0.1.0
    - name: Setup
      run: |
        rustup install 1.68.2
        rustup default 1.68.2
        rustup target add wasm32-unknown-unknown
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: |
        cargo build --release --target wasm32-unknown-unknown
        wasm-bindgen --out-dir ./out/ --target web ./target/wasm32-unknown-unknown/release/yausg.wasm
    - name: Copy in html
      run: cp index.html ./out/.
    - name: Copy in assets
      run: cp -r assets ./out/.
    - name: Zip
      run: |
        for f in $(chmod -c -R +r . | awk '{print substr($3, 2, length($3)-2)}')
        do
          echo "::warning::Added read permission to $f"
        done
        tar \
          --dereference --hard-dereference \
          --directory "./out/" \
          -cvf "$RUNNER_TEMP/artifact.tar" \
          --exclude=.git \
          --exclude=.github \
          .
    - name: Upload artifact
      uses: actions/upload-artifact@main
      with:
        name: github-pages
        path: ${{ runner.temp }}/artifact.tar
        retention-days: ${{ 1 }}
  deploy:
    needs: build
    permissions:
      pages: write #to deploy to Pages
      id-token: write #to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Deploy github.io page
      id: deployment
      uses: actions/deploy-pages@v1
